import { useEffect, useMemo, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";
import { Inspector } from "./inspector";
import { dagLayout, knowledgeLayout } from "./layout";
import LayoutWorker from "./layout.worker.ts?worker&inline";

type Mode = "all" | "tasks" | "knowledge";
type Kind = "parent" | "depends" | "wiki" | "affects";
type Node = { id: string; type: "task" | "knowledge"; title: string; status?: string; claim_kind?: string; progress?: number; path?: string; summary?: string; metadata?: Record<string, unknown> };
type Edge = { from: string; to: string; kind: Kind };
type Data = { schemaVersion?: number; initialMode?: Mode; tasks?: Record<string, Omit<Node, "id" | "type">>; knowledge?: Record<string, Omit<Node, "id" | "type">>; edges?: Edge[]; diagnostics?: { redlinks: string[] } };
type Point = { x: number; y: number };

const data = JSON.parse(document.querySelector("#hypha-data")?.textContent || "{}") as Data;
const nodes: Node[] = [...Object.entries(data.tasks || {}).map(([id, value]) => ({ id, type: "task" as const, ...value })), ...Object.entries(data.knowledge || {}).map(([id, value]) => ({ id, type: "knowledge" as const, ...value }))];
const edges = data.edges || [];
const visible = (mode: Mode, kind: Kind) => mode === "all" || (mode === "tasks" && ["parent", "depends"].includes(kind)) || (mode === "knowledge" && kind === "wiki");
function layout(items: Node[], mode: Mode) { if (mode === "tasks") return dagLayout(items, edges); if (mode === "knowledge") return knowledgeLayout(items, edges); const tasks = dagLayout(items.filter((node) => node.type === "task"), edges); const knowledge = knowledgeLayout(items.filter((node) => node.type === "knowledge"), edges); for (const position of knowledge.values()) position.x += 160; return new Map([...tasks, ...knowledge]); }

function Graph({ mode, selected, focused, highContrast, onSelect }: { mode: Mode; selected?: string; focused?: Set<string>; highContrast: boolean; onSelect: (node?: Node) => void }) {
  const canvas = useRef<HTMLCanvasElement>(null); const camera = useRef({ x: 0, y: 0, scale: 1 }); const gesture = useRef<{ x: number; y: number; node?: Node; position?: Point } | undefined>(undefined); const frame = useRef<number | undefined>(undefined);
  const shown = useMemo(() => nodes.filter((node) => (mode === "all" || node.type === (mode === "tasks" ? "task" : "knowledge")) && (!focused || focused.has(node.id))), [mode, focused]);
  const [positions, setPositions] = useState<Map<string, Point>>(new Map()); const large = shown.length > 150 || edges.length > 800;
  const shownEdges = useMemo(() => { const ids = new Set(shown.map((node) => node.id)); return edges.filter((edge) => visible(mode, edge.kind) && ids.has(edge.from) && ids.has(edge.to)); }, [mode, shown]);
  // Layout is external canvas state; synchronous replacement keeps mode changes deterministic.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { if (!large) { setPositions(layout(shown, mode)); return; } const worker = new LayoutWorker(); worker.onmessage = (event: MessageEvent<[string, Point][]>) => setPositions(new Map(event.data)); worker.postMessage({ mode: mode === "all" ? "tasks" : mode, nodes: shown, edges }); return () => worker.terminate(); }, [large, mode, shown]);
  const draw = (now = performance.now()) => { const element = canvas.current; if (!element) return; const rect = element.getBoundingClientRect(); const dpr = Math.min(devicePixelRatio || 1, 2); element.width = rect.width * dpr; element.height = rect.height * dpr; const ctx = element.getContext("2d"); if (!ctx) return; ctx.setTransform(dpr, 0, 0, dpr, 0, 0); ctx.fillStyle = highContrast ? "#fff" : "#f8fbf7"; ctx.fillRect(0, 0, rect.width, rect.height); const screen = (p: Point) => ({ x: p.x * camera.current.scale + camera.current.x, y: p.y * camera.current.scale + camera.current.y });
    const arrow = (a: Point, b: Point, color: string, branch: boolean) => { const dx = b.x - a.x; const dy = b.y - a.y; const length = Math.max(1, Math.hypot(dx, dy)); const ux = dx / length; const uy = dy / length; const end = { x: b.x - ux * 38, y: b.y - uy * 28 }; ctx.fillStyle = color; ctx.beginPath(); ctx.moveTo(end.x, end.y); ctx.lineTo(end.x - ux * 10 + uy * 5, end.y - uy * 10 - ux * 5); ctx.lineTo(end.x - ux * 10 - uy * 5, end.y - uy * 10 + ux * 5); ctx.closePath(); ctx.fill(); if (branch) { ctx.beginPath(); ctx.moveTo((a.x + end.x) / 2, (a.y + end.y) / 2); ctx.lineTo((a.x + end.x) / 2 - uy * 12 - ux * 8, (a.y + end.y) / 2 + ux * 12 - uy * 8); ctx.stroke(); } };
    for (const edge of shownEdges) { const from = positions.get(edge.from); const to = positions.get(edge.to); if (!from || !to) continue; const a = screen(from); const b = screen(to); const color = edge.kind === "wiki" ? "#6a4ca3" : edge.kind === "affects" ? "#b84a14" : edge.kind === "depends" ? "#126b49" : "#456c58"; ctx.strokeStyle = color; ctx.lineWidth = edge.kind === "affects" ? 2.6 : 1.5; ctx.globalAlpha = selected ? (edge.from === selected || edge.to === selected ? 1 : 0.25) : 0.82; ctx.setLineDash(edge.kind === "parent" ? [4, 5] : []); ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.quadraticCurveTo((a.x + b.x) / 2, (a.y + b.y) / 2 - 22, b.x, b.y); ctx.stroke(); ctx.setLineDash([]); if (edge.kind === "depends" || edge.kind === "affects") arrow(a, b, color, edge.kind === "affects"); if (!large && selected && (edge.from === selected || edge.to === selected)) { const t = (now % 1600) / 1600; ctx.fillStyle = color; ctx.globalAlpha = .75; ctx.beginPath(); ctx.arc(a.x + (b.x - a.x) * t, a.y + (b.y - a.y) * t, 3, 0, Math.PI * 2); ctx.fill(); } }
    ctx.globalAlpha = 1; for (const node of shown) { const position = positions.get(node.id); if (!position) continue; const p = screen(position); const task = node.type === "task"; ctx.save(); ctx.translate(p.x, p.y); ctx.fillStyle = highContrast ? "#fff" : task ? (node.status === "blocked" ? "#f9ddd0" : node.status === "done" ? "#d9f0df" : "#dcefe2") : "#eee4fb"; ctx.strokeStyle = selected === node.id ? "#111" : task ? "#126b49" : "#6a4ca3"; ctx.lineWidth = selected === node.id ? 3 : 1.5; ctx.beginPath(); if (task) ctx.roundRect(-82, -31, 164, 62, 14); else ctx.arc(0, 0, 36, 0, Math.PI * 2); ctx.fill(); ctx.stroke(); if (selected === node.id && !large) { ctx.strokeStyle = "#e17a1d"; ctx.globalAlpha = .4 + .35 * Math.sin(now / 180); ctx.lineWidth = 5; ctx.beginPath(); ctx.arc(0, 0, task ? 48 : 47, 0, Math.PI * 2); ctx.stroke(); ctx.globalAlpha = 1; } ctx.fillStyle = "#173326"; ctx.font = "12px system-ui"; ctx.fillText(`${node.id} · ${node.title}`.slice(0, 23), -72, -4); ctx.fillStyle = "#426653"; ctx.font = "10px system-ui"; ctx.fillText(node.status || node.claim_kind || "note", -72, 17); ctx.restore(); } };
  useEffect(() => { const resize = () => draw(); const observer = new ResizeObserver(resize); if (canvas.current) observer.observe(canvas.current); if (!large && selected && !matchMedia("(prefers-reduced-motion: reduce)").matches) { const animate = (time: number) => { draw(time); frame.current = requestAnimationFrame(animate); }; frame.current = requestAnimationFrame(animate); } else draw(); return () => { observer.disconnect(); if (frame.current) cancelAnimationFrame(frame.current); }; });
  const hit = (event: React.PointerEvent<HTMLCanvasElement>) => { const rect = canvas.current!.getBoundingClientRect(); const x = (event.clientX - rect.left - camera.current.x) / camera.current.scale; const y = (event.clientY - rect.top - camera.current.y) / camera.current.scale; return shown.slice().reverse().find((node) => { const p = positions.get(node.id); return p && Math.abs(x - p.x) < 82 && Math.abs(y - p.y) < 32; }); };
  return <><canvas ref={canvas} aria-label="Hypha 可交互菌丝关系图" onPointerDown={(event) => { const node = hit(event); canvas.current?.setPointerCapture(event.pointerId); gesture.current = { x: event.clientX, y: event.clientY, node, position: node ? { ...positions.get(node.id)! } : undefined }; }} onPointerMove={(event) => { const active = gesture.current; if (!active) return; const dx = event.clientX - active.x; const dy = event.clientY - active.y; if (active.node && active.position) setPositions((old) => new Map(old).set(active.node!.id, { x: active.position!.x + dx / camera.current.scale, y: active.position!.y + dy / camera.current.scale })); else { camera.current.x += dx; camera.current.y += dy; active.x = event.clientX; active.y = event.clientY; draw(); } }} onPointerUp={(event) => { const active = gesture.current; if (active && Math.hypot(event.clientX - active.x, event.clientY - active.y) < 5) onSelect(active.node); gesture.current = undefined; }} onWheel={(event) => { event.preventDefault(); camera.current.scale = Math.max(.25, Math.min(3, camera.current.scale * (event.deltaY < 0 ? 1.12 : .89))); draw(); }} />{large && <span className="large">大图模式：已关闭背景与粒子效果，并精简文字</span>}</>;
}

function App() { const [mode, setMode] = useState<Mode>(data.initialMode || "all"); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<Node>(); const [focused, setFocused] = useState<Set<string>>(); const [highContrast, setHighContrast] = useState(false); const matches = nodes.filter((node) => `${node.id} ${node.title} ${node.status || node.claim_kind || ""}`.toLowerCase().includes(query.toLowerCase())); const neighbors = selected ? new Set([selected.id, ...edges.filter((edge) => edge.from === selected.id || edge.to === selected.id).flatMap((edge) => [edge.from, edge.to])]) : new Set<string>(); useEffect(() => { const listener = (event: KeyboardEvent) => { if (event.key === "Escape") { setSelected(undefined); setFocused(undefined); } if (event.key === "/") { event.preventDefault(); document.querySelector<HTMLInputElement>("#search")?.focus(); } }; addEventListener("keydown", listener); return () => removeEventListener("keydown", listener); }, []); return <main className={highContrast ? "contrast" : ""}><header><div><h1>Hypha · Mycelial Canvas</h1><p>本地只读关系图 · 离线生成 · schema v{data.schemaVersion || 1}</p></div><span className="badge">红链 {data.diagnostics?.redlinks.length || 0}</span></header><nav aria-label="图模式">{(["all", "tasks", "knowledge"] as Mode[]).map((item) => <button key={item} aria-pressed={mode === item} className={mode === item ? "active" : ""} onClick={() => { setMode(item); setFocused(undefined); }}>{item === "all" ? "全部关系" : item === "tasks" ? "任务 DAG" : "知识关系"}</button>)}<button aria-pressed={highContrast} onClick={() => setHighContrast((value) => !value)}>高对比</button><input id="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索 ID、标题、状态" />{query && <div className="results">{matches.slice(0, 6).map((node) => <button key={node.id} onClick={() => { setSelected(node); setQuery(""); }}>{node.id} · {node.title}</button>)}</div>}</nav><section className="board"><div className="canvas"><Graph mode={mode} selected={selected?.id} focused={focused} highContrast={highContrast} onSelect={setSelected} /></div><aside aria-live="polite"><Inspector node={selected} edges={edges} onFocus={() => setFocused(neighbors)} /><p className="read-only">只读视图；状态变更请使用 Hypha CLI / draft / apply。</p></aside></section><div className="sr-only" aria-live="polite">{selected ? `已选择 ${selected.title}` : "未选择节点"}</div><ul className="sr-only" aria-label="节点列表">{nodes.map((node) => <li key={node.id}><button onClick={() => setSelected(node)}>{node.id} {node.title}</button></li>)}</ul></main>; }
createRoot(document.querySelector("#root")!).render(<App />);
