import { test, expect } from "@playwright/test";
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

test("generated view is offline and supports graph interaction", async ({ page }) => {
  const workspace = mkdtempSync(join(tmpdir(), "hypha-view-"));
  const cli = resolve("../skills/hypha-governance/scripts/hypha.py");
  const run = (...args: string[]) => execFileSync("python3", [cli, "--workspace", workspace, ...args]);
  run("init"); run("add", "Implement canvas"); run("add", "Review canvas", "0001");
  const draft = join(workspace, ".hypha", ".drafts", "knowledge.md");
  writeFileSync(draft, "---\nkind: know\nclaim_kind: note\naffects: [0001]\ntriggers: [canvas]\n---\n# Canvas evidence\n\n[[know/other]]\n");
  run("apply", draft);
  writeFileSync(join(workspace, ".hypha", "know", "other.md"), "---\nclaim_kind: note\n---\n# Other evidence\n\n[[know/knowledge]]\n");
  run("view");
  const html = readFileSync(join(workspace, ".hypha", "view.html"), "utf8");
  expect(html).toContain("data:,");
  const requests: string[] = []; page.on("request", (request) => requests.push(request.url()));
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.goto(`file://${join(workspace, ".hypha", "view.html")}`);
  await expect(page.getByText("Hypha Task Map")).toBeVisible();
  await expect(page.locator("canvas")).toHaveCount(0);
  await expect(page.locator(".react-flow__node")).toHaveCount(4);
  await expect(page.locator(".edge-wiki")).toHaveCount(1);
  await page.getByLabel("Status").selectOption("todo");
  await expect(page.locator(".react-flow__node")).toHaveCount(2);
  await page.getByLabel("Status").selectOption("all");
  await page.getByLabel("Type").selectOption("knowledge");
  await expect(page.locator(".react-flow__node")).toHaveCount(2);
  const resetFilters = page.getByRole("button", { name: "Reset filters" });
  await expect(resetFilters).toBeEnabled();
  await resetFilters.click();
  await expect(page.getByLabel("Type")).toHaveValue("all");
  await expect(page.locator(".react-flow__node")).toHaveCount(4);
  await page.getByRole("button", { name: "Tasks" }).click();
  await page.getByRole("button", { name: "Knowledge" }).click();
  await page.getByRole("button", { name: "⌘ Mycelium" }).click();
  await page.locator("#search").fill("Canvas evidence");
  await page.locator(".results").getByRole("button", { name: /Canvas evidence/ }).click();
  await expect(page.locator(".react-flow__node.selected")).toHaveCount(1);
  await expect(page.locator(".edge-flow")).toHaveCount(2);
  await expect(page.locator(".edge-flow").first()).toHaveCSS("filter", "none");
  await expect(page.locator(".edge-flow").first()).toHaveCSS("animation-timing-function", "steps(28)");
  const focus = page.getByRole("button", { name: "◎ Focus" });
  await expect(focus).toBeEnabled();
  await focus.click();
  await expect(focus).toHaveAttribute("aria-pressed", "true");
  await expect(page.locator(".react-flow__node")).toHaveCount(3);
  await resetFilters.click();
  await expect(focus).toHaveAttribute("aria-pressed", "false");
  await page.screenshot({ path: "test-results/selected-node.png", fullPage: true });
  await expect(page.getByRole("complementary")).toContainText("Canvas evidence");
  await expect(page.getByRole("complementary")).toContainText("Metadata");
  await expect(page.getByRole("complementary")).toContainText("Markdown content");
  await expect(page.getByRole("complementary")).toContainText("[[know/other]]");
  const previousNode = page.getByRole("button", { name: "Previous node" });
  const nextNode = page.getByRole("button", { name: "Next node" });
  await expect(previousNode).toBeDisabled();
  await page.getByRole("complementary").getByRole("button", { name: /0001.*Implement canvas/ }).click();
  await expect(page.getByRole("complementary")).toContainText("Implement canvas");
  await expect(previousNode).toBeEnabled();
  await expect(nextNode).toBeDisabled();
  await previousNode.click();
  await expect(page.getByRole("complementary")).toContainText("Canvas evidence");
  await expect(nextNode).toBeEnabled();
  await nextNode.click();
  await expect(page.getByRole("complementary")).toContainText("Implement canvas");
  await page.keyboard.press("Escape");
  await expect(page.getByRole("complementary")).toContainText("Node details");
  const graph = page.getByLabel("Interactive Hypha relationship graph");
  const box = await graph.boundingBox(); if (!box) throw new Error("graph missing");
  await graph.hover({ position: { x: box.width / 2, y: box.height / 2 } }); await page.mouse.wheel(0, -180); await page.mouse.move(box.x + 120, box.y + 120); await page.mouse.down(); await page.mouse.move(box.x + 170, box.y + 150); await page.mouse.up();
  await page.screenshot({ path: "test-results/mycelial-canvas.png", fullPage: true });
  expect(requests.every((url) => url.startsWith("file:") || url.startsWith("data:"))).toBeTruthy();
});
